version: "3.5"
services:
  web:
    container_name: django-blog-container
    build: .
    restart: always
    ports:
      - "808:808"
      - "5002:5002"
    # command: 
    #   - /bin/bash
    #   - -c
    #   - |
    #    python3 manage.py migrate
    #    python3 -m populate.all 
    volumes:
      - django_web:/web
    depends_on:
      - db
      - redis

  db:
    container_name: postgres-django
    image: postgres
    environment:
      POSTGRES_USER: djangodb
      POSTGRES_PASSWORD: 5432
    volumes:
      - pgdata-django:/var/lib/postgresql/data/

  redis:
    container_name: django-redis
    image: redis:alpine
    restart: always

volumes:
  pgdata-django:
  django_web: