version: "3.5"
services:
  web:
    container_name: django-blog-container
    build: .
    restart: always
    ports:
      - "808:808"
    command: 
      - /bin/sh
      - -c
      - |
        service nginx start
        python3 populate.py
        gunicorn -w 3 run:app
    volumes:
      - web:/web
    depends_on:
      - db

  db:
    container_name: postgres-django
    image: postgres
    environment:
      POSTGRES_USER: flaskdb
      POSTGRES_PASSWORD: 5432
    volumes:
      - pgdata-django:/var/lib/postgresql/data/

volumes:
  pgdata-django:
  web: