# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 12:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
