# Generated by Django 2.0.7 on 2018-07-17 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import extra_apps.ckeditor_uploader.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guestbook_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, unique=True)),
                ('pubDateTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '留言板分类',
                'verbose_name_plural': '留言板分类',
                'ordering': ['-pubDateTime'],
            },
        ),
        migrations.CreateModel(
            name='Guestbook_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True, verbose_name='标题')),
                ('content', extra_apps.ckeditor_uploader.fields.RichTextUploadingField(verbose_name='正文')),
                ('pubDateTime', models.DateTimeField(auto_now_add=True, verbose_name='发表时间')),
                ('upDateTime', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('comment_num', models.IntegerField(default=0, verbose_name='评论数')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='guestbook.Guestbook_Category', verbose_name='分类')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='(选填)用英文输入法逗号来分割标签', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': '留言板文章',
                'verbose_name_plural': '留言板文章',
                'ordering': ['-pubDateTime'],
            },
        ),
    ]
