# Generated by Django 2.0.7 on 2018-08-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='subtitle_list',
        ),
        migrations.AddField(
            model_name='article',
            name='is_subtitle_list',
            field=models.BooleanField(default=False),
        ),
    ]
