# Generated by Django 2.0.7 on 2018-10-20 11:14

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_article', '0002_auto_20180823_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_thumbnail',
            field=models.BooleanField(default=False, verbose_name='是否生成封面'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumb_type',
            field=models.CharField(choices=[('不添加', 'none'), ('以内容第一张图片作为封面', 'cimg'), ('标题词云', 'wc'), ('自定义封面', 'custom')], default='不添加', max_length=20, verbose_name='生成封面类型'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default=None, null=True, upload_to='thumbnail', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_subtitle_list',
            field=models.BooleanField(default=False, verbose_name='是否生成目录'),
        ),
    ]
