# Generated by Django 2.0.7 on 2018-10-20 11:32

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_article', '0003_auto_20181020_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumb_type',
            field=models.CharField(choices=[('NONE', '不添加'), ('CIMG', '以内容第一张图片作为封面'), ('WC', '标题词云'), ('CUSTOM', '自定义封面')], default='NONE', max_length=20, verbose_name='生成封面类型'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to='thumbnail', verbose_name='封面'),
        ),
    ]
