# Generated by Django 2.0.7 on 2018-10-21 16:26

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main_article', '0004_auto_20181020_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default=None, null=True, upload_to='title', verbose_name='封面'),
        ),
    ]
